[package]
name = "memfd-ipc"
version = "0.1.0"
authors = ["David Henningsson <coding@diwic.se>"]
edition = "2018"

[dependencies]
memfd = "0.3"
memmap2 = { path="../memmap2-rs" } # , git = "https://github.com/diwic/memmap2-rs.git" }
# memfd depends on thiserror, so we can depend on it too without causing
# additional dependencies.
thiserror = "1"
