[package]
name = "memfd-ipc"
version = "0.1.0"
authors = ["David Henningsson <coding@diwic.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
